# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Project Tests


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest dvc
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download data
      run: |
        python3.10 src/download_data.py
    - name: Test dataset
      run: |
        pytest tests/test_dataset.py
    - name: Preprocessing
      run: |
        python3.10 src/preprocessing.py
    - name: Train model
      run: |
        python3 src/train_model.py
        dvc add models/rfc_model.pkl
    - name: Metrics
      run: |
        python3.10 src/metrics.py
    - name: Test model
      run: |
        pytest tests/test_model.py
    - name: Preprocessing
      run: |
        python3.10 src/preprocessing.py